name: builds

on: push

jobs:
  create-builds:
    name: Create distributable builds
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            python-version: 3.8

          - os: macos-10.15
            python-version: 3.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bundle JRE
        run: |
          python ./scripts/getjdk.py --binary --feature-version 11 --image-type jre --extract-to resources
          mv resources/jdk* resources/java

      - name: Install python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/dev.in

      - name: Package application (archive)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          python setup.py standalone

      - name: Package application (dmg)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          python setup.py createdmg

      - name: Upload artifact (GitHub)
        uses: actions/upload-artifact@v2
        with:
          name: Eddy-${{ runner.os }}
          path: dist/*

      - run: |
          echo EDDY_VERSION="$(python -c 'import eddy; print(eddy.VERSION)')" >> $GITHUB_ENV

      - name: Upload artifact (Bintray)
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          python -m pip install bintray-python==0.8.0
          python ./scripts/bintray_upload.py \
            --username ${{ secrets.BINTRAY_API_USER }} \
            --api-key ${{ secrets.BINTRAY_API_KEY }} \
            --subject ${{ secrets.BINTRAY_REPO_USER }} \
            --repo ${{ secrets.BINTRAY_REPO}} \
            --package Eddy \
            --version ${{ env.EDDY_VERSION }} \
            --publish \
            --override \
            dist/*
