name: builds

on: push

jobs:
  create-builds:
    name: Create distributable builds
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            python-version: 3.8
            pyqt-version: 5.15

          - os: macos-10.15
            python-version: 3.8
            pyqt-version: 5.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bundle JRE
        run: |
          ./scripts/getjdk.py --binary --feature-version 11 --image-type jre --extract-to resources
          mv resources/jdk* resources/java

      - name: Install python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/dev.in

      - name: Package application (archive)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          python setup.py standalone

      - name: Package application (dmg)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          python setup.py createdmg

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Eddy-${{ runner.os }}
          path: dist/*

